# -*- coding: utf-8 -*-
"""ManejoArchivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQmZB13qGTx8l0tqeQGh3BespkiWgKAw
"""

from google.colab import drive
drive.mount('/content/drive')

# Import PyDrive and associated libraries.
# This only needs to be done once per notebook.
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import os

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

gauth.SaveCredentialsFile("mycreds.txt")

ruta = r'/content/drive/MyDrive/Educación/UADE'

os.chdir(ruta) # replace '/script_directory_path' with your original script path, and place this code above 'gauth = GoogleAuth()' in your script.
print(os.getcwd())

#ID de la ruta destino se toma de Google Drive (ver como tomarlo por código)
parentID = '1dZagzjduuxk4NpwGvGHbNKcPYGpmmjEH' 
file = drive.CreateFile({'title': 'MiArchivo.txt', 
                         'parents': [{"id": parentID}]
                         })
file.SetContentString('Hello World!') # this writes a string directly to a file
file.Upload()
print('Uploaded file with ID {}'.format(file.get('id')))

file.Trash()

folder = drive.CreateFile({'title': 'MyCarpetaCompartida', "mimeType": "application/vnd.google-apps.folder"})
folder.Upload()
# Insert the permission.
permission = folder.InsertPermission({
    'type': 'user',
    'value': 'perito029@gmail.com',
    'role': 'writer'
})
print(folder['alternateLink'])  # Display the sharable link.

folder.Trash()

!ls -la /content/drive/MyDrive/Educación/UADE

# List .txt files in the root.
#
# Search query reference:
# https://developers.google.com/drive/v2/web/search-parameters
listed = drive.ListFile({'q': "title contains 'UADE' and 'root' in parents"}).GetList()
for file in listed:
  print('title {}, id {}'.format(file['title'], file['id']))